Partly resolved the problem related to GNU multiprecision library.
git-svn-id: svn+ssh://circa.ecs.vuw.ac.nz/u/staff/djp/projects/repository/tuttepoly/trunk@1251 cab769db-1af3-0310-8bf3-f2d376eea66d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3886,12 +3886,12 @@ else
 fi
 
 
-# Checks for libraries.
+# Checks for GNU Multiple Precision (GMP) library.
 
 
-{ echo "$as_me:$LINENO: checking for mpz_pow_ui in -lgmp" >&5
-echo $ECHO_N "checking for mpz_pow_ui in -lgmp... $ECHO_C" >&6; }
-if test "${ac_cv_lib_gmp_mpz_pow_ui+set}" = set; then
+{ echo "$as_me:$LINENO: checking for __gmpz_add in -lgmp" >&5
+echo $ECHO_N "checking for __gmpz_add in -lgmp... $ECHO_C" >&6; }
+if test "${ac_cv_lib_gmp___gmpz_add+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
@@ -3909,11 +3909,11 @@ cat >>conftest.$ac_ext <<_ACEOF
 #ifdef __cplusplus
 extern "C"
 #endif
-char mpz_pow_ui ();
+char __gmpz_add ();
 int
 main ()
 {
-return mpz_pow_ui ();
+return __gmpz_add ();
   ;
   return 0;
 }
@@ -3936,21 +3936,21 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_gmp_mpz_pow_ui=yes
+  ac_cv_lib_gmp___gmpz_add=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_gmp_mpz_pow_ui=no
+	ac_cv_lib_gmp___gmpz_add=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_gmp_mpz_pow_ui" >&5
-echo "${ECHO_T}$ac_cv_lib_gmp_mpz_pow_ui" >&6; }
-if test $ac_cv_lib_gmp_mpz_pow_ui = yes; then
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_gmp___gmpz_add" >&5
+echo "${ECHO_T}$ac_cv_lib_gmp___gmpz_add" >&6; }
+if test $ac_cv_lib_gmp___gmpz_add = yes; then
   cat >>confdefs.h <<_ACEOF
 #define HAVE_LIBGMP 1
 _ACEOF
@@ -3959,6 +3959,71 @@ _ACEOF
 
 fi
 
+
+{ echo "$as_me:$LINENO: checking for main in -lgmpxx" >&5
+echo $ECHO_N "checking for main in -lgmpxx... $ECHO_C" >&6; }
+if test "${ac_cv_lib_gmpxx_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgmpxx  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_gmpxx_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_gmpxx_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_gmpxx_main" >&5
+echo "${ECHO_T}$ac_cv_lib_gmpxx_main" >&6; }
+if test $ac_cv_lib_gmpxx_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBGMPXX 1
+_ACEOF
+
+  LIBS="-lgmpxx $LIBS"
+
+fi
+ # use special symbol "main" as I don't know about to resolve name mangling.
 
 # Checks for header files.
 ac_ext=c
